### ISSUE TITLE
Add Anime4K models

### ISSUE THREAD

**Issue by arianaa30** [muslll/neosr#53]
Very useful repo. Can you please add Anime4K models too?
I guess we need a anime4k_arch.py and a .yaml file. I tried something myself, but the .pth was only 70kb. So not sure if I did things correctly.

**Comment by muslll** [comment]
Hi @arianaa30! Sorry for my late reply. The Anime4k network has been surpassed (afaik) by many others on neosr, such as compact, span and omnisr (although they are a bit slower). I'd recommend you testing those first.
If you really need Anime4k, porting the code is very easy, because other people already did all the work (thanks @kato-megumi ). All you have to do is create a new file called "anime4k_arch.py", copy-paste the code bellow and move that file inside the folder [neosr/neosr/archs/](https://github.com/muslll/neosr/tree/master/neosr/archs):

```
import torch
from torch import nn
from torch.nn import functional as F

from neosr.utils.registry import ARCH_REGISTRY
from .arch_util import net_opt

upscale, training = net_opt()


def conv_layer(in_channels, out_channels, kernel_size):
    padding = int((kernel_size - 1) / 2)
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=padding)


class CReLU(nn.Module):
    def __init__(self):
        super(CReLU, self).__init__()

    def forward(self, x):
        return F.relu(torch.cat((x, -x), 1))


@ARCH_REGISTRY.register()
class anime4k(nn.Module):
    def __init__(
        self, block_depth=7, stack_list=5, num_feat=12, act="crelu", last=False
    ):
        super(anime4k, self).__init__()
        if act == "crelu":
            factor = 2
            self.act = CReLU()
        elif act == "prelu":
            factor = 1
            self.act = nn.PReLU(num_parameters=num_feat)
        if type(stack_list) == int:
            stack_list = list(range(-stack_list, 0))
        self.stack_list = stack_list
        self.ps = nn.PixelShuffle(2)

        self.conv_head = conv_layer(3, num_feat, kernel_size=3)
        self.conv_mid = nn.ModuleList([
            conv_layer(num_feat * factor, num_feat, kernel_size=3)
            for _ in range(block_depth - 1)
        ])
        if last:
            self.conv_tail = conv_layer(
                factor * num_feat * len(stack_list), 12, kernel_size=3
            )
        else:
            self.conv_tail = conv_layer(
                factor * num_feat * len(stack_list), 12, kernel_size=1
            )

    def forward(self, x):
        out = self.act(self.conv_head(x))
        depth_list = [out]
        for conv in self.conv_mid:
            out = self.act(conv(out))
            depth_list.append(out)
        out = self.conv_tail(torch.cat([depth_list[i] for i in self.stack_list], 1))
        out = self.ps(out) + F.interpolate(x, scale_factor=upscale, mode="bilinear")
        return torch.clamp(out, max=1.0, min=0.0)
```

Then to train, all you have to do is specify to use the `anime4k` network:

```
network_g:
    type: anime4k
```

**Comment by arianaa30** [comment]
@muslll Thanks. Yeah I copied the Anime4K from our thread (with kato). I trained but the generated network_g was only 74kb. Wasn't sure things are correct.

Is this option sounds correct to you? I modified the compact arch and modified only `network_g` line:

```
name: train_anime4k
model_type: default
scale: 2
use_amp: false
bfloat16: false
fast_matmul: false
compile: false
#manual_seed: 1024

datasets:
  train:
    type: paired
    dataroot_gt: 'datasets/gt/'
    dataroot_lq: 'datasets/lq/'
    #meta_info: 'datasets/meta_info.txt'
    io_backend:
      type: disk

    gt_size: 128
    batch_size: 6
    accumulate: 1
    use_hflip: true
    use_rot: true
    dataset_enlarge_ratio: 5

#  val:
#    name: val_1
#    type: paired 
#    dataroot_gt: 'datasets/val/gt/'
#    dataroot_lq: 'datasets/val/lq/'
#    io_backend:
#      type: disk
#val:
#  val_freq: 1000
#  save_img: true
#  metrics:
#    psnr:
#      type: calculate_psnr
#    ssim:
#      type: calculate_ssim

path:
  #pretrain_network_g: 'experiments/pretrain.pth'
  resume_state: ~
  #strict_load_g: false # do not uncomment, read docs

network_g:
  type: anime4k 

network_d:
  type: unet

train:
  optim_g:
    type: adamw
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: adamw
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: multisteplr
    milestones: [60000, 120000]
    gamma: 0.5

  total_iter: 500
  warmup_iter: -1  # no warm up
  grad_clip: false

  # losses
  pixel_opt:
    type: HuberLoss
    loss_weight: 1.0
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    perceptual_weight: 1.0
    style_weight: 0
    criterion: huber
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: 0.1
  #ldl_opt:
  #  type: HuberLoss
  #  loss_weight: 1.0
  #ff_opt:
  #  type: focalfrequencyloss
  #  loss_weight: 0.5

#  match_lq: false
#  color_opt:
#    type: colorloss
#    loss_weight: 1.0
#    criterion: l1
#  luma_opt:
#    type: lumaloss
#    loss_weight: 1.0
#    criterion: l1

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true

```

**Comment by muslll** [comment]
@arianaa30 Looks correct, yes. The `gt_size` is double the default (because, [remember](https://github.com/muslll/neosr/wiki/Configuration-Walkthrough#gt_size), it depends on your `scale`). But if you don't run out of vram, that's fine.
About the model being only 74kb, that could be correct also, since anime4k is a very lightweight network. I'd recommend you training it for some iters and then testing it using the [test.py](https://github.com/muslll/neosr/blob/master/test.py) script. Simply modify one of the test [templates](https://github.com/muslll/neosr/blob/master/options/test_compact.yml) to use anime4k, link your model on `pretrain_model_g` and run it:
```
python test.py -opt your_test_config.yml
```
Results will be saved on experiments/results/. If the results look like an image, then it's working :smile:

**Comment by muslll** [comment]
Just tested it myself, and it converges as it should. Indeed the models are only 74kb, but it works ok.

**Comment by muslll** [comment]
Example for only 20k iters:
![anime4k_neosr_22k](https://github.com/muslll/neosr/assets/132400428/8b0b1a3b-4013-4a51-b82c-d24f51d9af5b)
Model: [anime4k_20k.zip](https://github.com/muslll/neosr/files/14550894/anime4k_20k.zip)

**Comment by muslll** [comment]
I have updated the original code from @kato-megumi to add other upscaling ratios and dropout (can help improve generalization on realistic models, values are 0.0-1.0, recommended: <=0.5):
```python
import torch
from torch import nn
from torch.nn import functional as F

from neosr.utils.registry import ARCH_REGISTRY
from .arch_util import net_opt

upscale, training = net_opt()


def conv_layer(in_channels, out_channels, kernel_size):
    padding = int((kernel_size - 1) / 2)
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=padding)


class CReLU(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return F.relu(torch.cat((x, -x), 1))


@ARCH_REGISTRY.register()
class anime4k(nn.Module):
    def __init__(
        self,
        block_depth=7,
        stack_list=5,
        num_feat=12,
        upscale=upscale,
        act="crelu",
        dropout=0,
        last=False,
        **kwargs,
    ):
        super().__init__()

        if act == "crelu":
            factor = 2
            self.act = CReLU()
        elif act == "prelu":
            factor = 1
            self.act = nn.PReLU(num_parameters=num_feat)

        if type(stack_list) == int:
            stack_list = list(range(-stack_list, 0))

        self.stack_list = stack_list
        self.upscale = upscale
        self.ps = nn.PixelShuffle(upscale)
        self.dropout = nn.Dropout2d(dropout)

        self.conv_head = conv_layer(3, num_feat, kernel_size=3)
        self.conv_mid = nn.ModuleList([
            conv_layer(num_feat * factor, num_feat, kernel_size=3)
            for _ in range(block_depth - 1)
        ])
        if last:
            self.conv_tail = conv_layer(
                factor * num_feat * len(stack_list), 12, kernel_size=3
            )
        else:
            if upscale == 1:
                self.conv_tail = conv_layer(
                    factor * num_feat * len(stack_list), 3, kernel_size=1
                )
            if upscale == 2:
                self.conv_tail = conv_layer(
                    factor * num_feat * len(stack_list), 12, kernel_size=1
                )
            if upscale >= 4:
                self.conv_tail = conv_layer(
                    factor * num_feat * len(stack_list), 12 * upscale, kernel_size=1
                )

    def forward(self, x):
        out = self.act(self.conv_head(x))
        depth_list = [out]
        for conv in self.conv_mid:
            out = self.act(conv(out))
            depth_list.append(out)
        out = self.conv_tail(torch.cat([depth_list[i] for i in self.stack_list], 1))
        # dropout
        out = self.dropout(out)

        if self.upscale != 1:
            out = self.ps(out) + F.interpolate(
                x, scale_factor=self.upscale, mode="bilinear"
            )
        else:
            out = out + x

        return torch.clamp(out, max=1.0, min=0.0)
```

**Comment by arianaa30** [comment]
How to define the path to the `model.pth`? Isn't it the name of model simply in \experiment\train_anime4k\net_g_latest.pth like below? I just entered the final pth name.
But I get this error:

    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'net_g_latest.pth'

```
# Results will be saved to neosr/experiments/results/
name: test_anime4k
model_type: default
scale: 2
use_amp: false
compile: false

datasets:
  test_1:  
    name: val_1
    type: single
    dataroot_lq: 'datasets/val/'
    io_backend:
      type: disk

network_g:
  type: anime4k

path:
  pretrain_network_g: 'net_g_latest.pth'
  #strict_load_g: false # do not uncomment, read docs

val:
  save_img: true
  suffix: ~

```
